import "~/styles/globals.css";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { ClientProviders } from "./_components/Providers";
import Link from "next/link";
import { createClient } from "~/utils/supabase/server";
import Navigation from "./_components/navigation";
import { Suspense } from "react";
import { Loading } from "./_components/Loading";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: {
    template: "%s - t3-supabase-template",
    default: "SACCIM"
  },
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="ja" className={`${GeistSans.variable}`}>
      <body>
        <ClientProviders>
          <Toaster/>
          <header>
            <h1>SACCIM</h1>
            <Suspense fallback={<Loading/>}><WithAuthLayout/></Suspense>
          </header>
          <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
            {children}
          </main>
          <footer>powered by T3Stack and supabase</footer>
        </ClientProviders>
      </body>
    </html>
  );
}

async function WithAuthLayout() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser()
  return <>
  <Navigation authorized={!!user} />
  {user && <div>{user.email}でログイン済み</div>}
  </>
}
