import "~/styles/globals.css";
import UserMenu from "./_components/UserMenu";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import Link from "next/link";

export const metadata: Metadata = {
  title: {
    template: "%s - t3-supabase-template",
    default: "t3-supabase-template"
  },
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="ja" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>
          {children}
          <footer>powered by T3Stack and supabase</footer>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
